### ISSUE TITLE
Pytracking not found when running demo.

### ISSUE THREAD

**Issue by trathpai** [tongtybj/TrTr#1]
When running demo , pytracking is not found.

**Comment by tongtybj** [comment]
Did you run  ```$ ./install.sh ~/anaconda3 trtr ``` first?
Or you directly do https://github.com/tongtybj/TrTr/blob/master/install.sh#L24

**Comment by trathpai** [comment]
I ran the $ `./install.sh ~/anaconda3 trtr` first .

**Comment by tongtybj** [comment]
I am very sorry about the bug, which has been fixed by #3 
Please run `./install.sh ~/anaconda3 trtr` and then test `demo.py`  again with the latest master branch

**Comment by trathpai** [comment]
Thanks it is resolved.
