### ISSUE TITLE
Training Problem

### ISSUE THREAD

**Issue by FukushimaDaiki** [tongtybj/TrTr#10]
![layer_error](https://user-images.githubusercontent.com/52403265/129308427-c484aa42-be78-4088-94d0-eba3bd21fe18.png)

When I run main.py to training, occuring this problem:

> "RuntimeError: Error(s) in loading state_dict for TRTR:"

I don't know how to change the argument.

**Comment by tongtybj** [comment]
I hope you have figured out the error reason. 

Option of `--resume networks/trtr_resnet50.pth` is to load the trained model (`trtr_resenet50.pth`). However, this trained model only have one encoder layer and one decoder layer, which does not match your new training parameters. So you have to remove this option.

**Comment by FukushimaDaiki** [comment]
Thank you for your reply.
I could understand the problems.
