### ISSUE TITLE
About dataset creation for det and yt_bb

### ISSUE THREAD

**Issue by FukushimaDaiki** [tongtybj/TrTr#11]
I tried to download and create data sets for **det** and **yt_bb**.
The README says to use `par_crop.py` and `curate_video.py` each, but there is only `curate.py` in the folder.
Also, when I run **det**, **yt_bb's** `curate.py`, the content of the JSON file is only "{}" in both cases.

![スクリーンショット (45)](https://user-images.githubusercontent.com/52403265/132797317-293dba33-ba24-4b98-9474-10ffe3dd3e5e.png)

**Comment by tongtybj** [comment]
- For ILSVRC2015_DET (det), we could not get good training result. So we excluded this dataset in our default [parameters](https://github.com/tongtybj/TrTr/blob/master/parameters/train/default.yaml#L6), and I have to admit that there is some bug in   https://github.com/tongtybj/TrTr/tree/master/datasets/det

- For youtube_boudingbox(yt_bb), please check the readme of https://github.com/tongtybj/TrTr/tree/master/datasets/yt_bb

**Comment by FukushimaDaiki** [comment]
Thank you for your reply.
I could understand the problems.
