### ISSUE TITLE
We can not download model from Google Driver

### ISSUE THREAD

**Issue by HonglinChu** [tongtybj/TrTr#4]
https://drive.google.com/uc\?id\=1WSX3_QhwL8eqjqLSfLmB8iVMyqYpmOp6

Not Found
error 404

**Comment by tongtybj** [comment]
Yes, this is the URL link for command-line process. So you can not access the website by this URL.
I guess you did not try https://github.com/tongtybj/TrTr/blob/master/install.sh#L89 .
If you do not  want to use (or cannot) `gdown`, you then need to download manually. 

Generally, with the ${file_id}, you can download from web browser by access to `https://drive.google.com/file/d/${file_id}/view`. 
The ${file_id} in this case is `1WSX3_QhwL8eqjqLSfLmB8iVMyqYpmOp6`

**Comment by HonglinChu** [comment]
Thank you very much. By referring to your suggestions, I successfully downloaded the model （https://drive.google.com/file/d/1WSX3_QhwL8eqjqLSfLmB8iVMyqYpmOp6/view）
