### ISSUE TITLE
trtr_resnet50.pth 

### ISSUE THREAD

**Issue by swan2015** [tongtybj/TrTr#6]
we can not download the trained network trtr_resnet50.pth through the link in install.sh

**Comment by tongtybj** [comment]
Can you past the log of running `install.sh` here?

**Comment by tongtybj** [comment]
Can you directly access and download from following URL?
https://drive.google.com/file/d/1WSX3_QhwL8eqjqLSfLmB8iVMyqYpmOp6/view

Can you access to Google in your enviroment?

**Comment by swan2015** [comment]
I can access to Google, but can not download from following URL directly.

**Comment by tongtybj** [comment]
It is wired... I can access to the above URL right now... 

You can send a request email to chou@jsk.imi.i.u-tokyo.ac.jp, I will then reply and attach the model

**Comment by swan2015** [comment]
thank you!
