### ISSUE TITLE
TrTr_Test Problem

### ISSUE THREAD

**Issue by DavidZhangdw** [tongtybj/TrTr#7]
![image](https://user-images.githubusercontent.com/35833888/126889435-d866a995-7ccc-4319-b3b6-9f831238ee68.png)

![image](https://user-images.githubusercontent.com/35833888/126889441-41a215a2-a8e0-439b-b33f-0bec82759b3d.png)

I run the test.py for VOT2018, but raise an error: Benchmark dataset inference error: 'Configuration check failed:: No action for key 'tracker.model.backbone.transformer.enc_layers' to chenck value'。

Do you occur this problem, and how to solve it？

**Comment by tongtybj** [comment]
This bug should be solved by #8 . Please try that PR branch and tell me the result.

**Comment by DavidZhangdw** [comment]
Thanks, It works now.
